name: Tests

on: [push, pull_request]

jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Pre-Commit Checks
        run: |
          python -m pip install pip --upgrade
          pip install pre-commit
          pre-commit run -a

      - name: Analysis (git diff)
        if: failure()
        run: git diff

  package:
    name: Build & Verify Package
    needs: pre-commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to master
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Build and check with twine
        run: |
          python -m pip install pip --upgrade
          pip install twine setuptools wheel
          python setup.py sdist bdist_wheel
          ls -l dist
          python -m twine check dist/*
